### PR TITLE
Setting primary GID for users to be created from config.

### PR DESCRIPTION
**Pull request by MrDonkey07**
Setting primary GID for users to be created from config.

Rather than creating default individual groups for each user when calling `useradd`, the specified GID for that user will be used as the user's primary group. This ensures that files created by that user inside the container are correctly owned by the specified host GID.

### CODE REVIEW

**Comment by winromulus** [comment]
I'm going to keep this open for a bit because:
1. I don't have a stable dev environment right now
2. The pipeline is dependent on some secrets and need to refactor that one  first
3. This requires QUITE a bit of testing before being merged

I'm hoping to tackle this during this holiday season when I have more free time.

**Comment by fliot** [comment]
I faced the GID:1001 hardcoded issue,
I just reused the MrDonkey07 branch, and I herbly confirm it solved the issue.
Thanks !
**If I may, I vote for merge request approval.**

**Comment by FingerlessGlov3s** [comment]
Also hitting the default 1001 bug.

**Comment by torsteinelv** [comment]
update?

**Review by winromulus — COMMENTED** [review]
LGTM

**Review by winromulus — APPROVED** [review]
LGTM

**Pull request merged**
